spring.application.name=NoSQL-Project


server.servlet.context-path=/test

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=employee
spring.mongodb.username=employee_user
spring.mongodb.password=employee_pwd

kafka.bootstrap-servers=localhost:9091
server.port=8000
spring.data.mongodb.auto-index-creation=true